[package]
name = "p2pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggrs = "0.5.1"
macroquad = "0.3.10"
bincode = "1.3.3"
serde = "1.0.130"
glam = { version = "0.14.0", features = ["serde"] }